CONFIG_NAME: sepehr-phase2
PRESET_BASE: mainnet

TERMINAL_TOTAL_DIFFICULTY: 33792

MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 256
MIN_GENESIS_TIME: 1578009600
GENESIS_FORK_VERSION: 0x00007331
GENESIS_DELAY: 10

ALTAIR_FORK_VERSION: 0x01007331
ALTAIR_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x02007331
BELLATRIX_FORK_EPOCH: 1
CAPELLA_FORK_VERSION: 0x03007331
CAPELLA_FORK_EPOCH: 4294967295
DENEB_FORK_VERSION: 0x04007331
DENEB_FORK_EPOCH: 4294967295
ELECTRA_FORK_VERSION: 0x05007331
ELECTRA_FORK_EPOCH: 4294967295
FULU_FORK_VERSION: 0x06007331
FULU_FORK_EPOCH: 4294967295
GLOAS_FORK_VERSION: 0x07007331
GLOAS_FORK_EPOCH: 4294967295

SECONDS_PER_SLOT: 12
SLOT_DURATION_MS: 12000
SECONDS_PER_ETH1_BLOCK: 2
SLOTS_PER_EPOCH: 8
EPOCHS_PER_ETH1_VOTING_PERIOD: 2
ETH1_FOLLOW_DISTANCE: 8

MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 1
MAX_VALIDATORS_PER_WITHDRAWALS_SWEEP: 128
SHARD_COMMITTEE_PERIOD: 4
INACTIVITY_SCORE_BIAS: 4
INACTIVITY_SCORE_RECOVERY_RATE: 16
EJECTION_BALANCE: 16000000000
MIN_PER_EPOCH_CHURN_LIMIT: 2
CHURN_LIMIT_QUOTIENT: 65536
PROPOSER_SCORE_BOOST: 40

DEPOSIT_CHAIN_ID: 7331
DEPOSIT_NETWORK_ID: 7331
DEPOSIT_CONTRACT_ADDRESS: 0xf2e246bb76df876cef8b38ae84130f4f55de395b

INACTIVITY_PENALTY_QUOTIENT_ALTAIR: 50331648
MIN_SLASHING_PENALTY_QUOTIENT_ALTAIR: 64
PROPORTIONAL_SLASHING_MULTIPLIER_ALTAIR: 2
SYNC_COMMITTEE_SIZE: 512
EPOCHS_PER_SYNC_COMMITTEE_PERIOD: 8
MIN_SYNC_COMMITTEE_PARTICIPANTS: 1
MAX_SEED_LOOKAHEAD: 1
